### ISSUE TITLE
Inconsistent file downloads from s3fs 0.2.* -> 0.3.*

### ISSUE THREAD

**Issue by ewellinger** [dask/s3fs#232] opened 2019-08-29 20:34 UTC
I'm noticing corrupted file downloads for _some_ files when using `s3fs` 0.3.*.  The problem manifested itself when I was unable to load in certain part files of a parquet file into either spark or dask after downloading them from an s3 bucket.  In spark it was manifesting itself as a `java.io.IOException: Could not read footer for file` error.

After some investigating I determined that `s3fs` was producing different md5 hashes from using `boto3` directly.  I further isolated the issue to the 0.3.* update.  The following shows the breakdown of the same file downloaded with `boto3` and `s3fs` and then run through the md5 hash digest:

```
boto3==1.9.202
s3fs==0.2.0
Hash produced with boto3: 66793fed3e21e38ebc46493a9e8c46c4
Hash produced with s3fs: 66793fed3e21e38ebc46493a9e8c46c4

boto3==1.9.202
s3fs==0.2.1
Hash produced with boto3: 66793fed3e21e38ebc46493a9e8c46c4
Hash produced with s3fs: 66793fed3e21e38ebc46493a9e8c46c4

boto3==1.9.202
s3fs==0.2.2
Hash produced with boto3: 66793fed3e21e38ebc46493a9e8c46c4
Hash produced with s3fs: 66793fed3e21e38ebc46493a9e8c46c4

boto3==1.9.202
s3fs==0.3.0
Hash produced with boto3: 66793fed3e21e38ebc46493a9e8c46c4
Hash produced with s3fs: c86cf89971dfb3806166afc92a050492

boto3==1.9.202
s3fs==0.3.1
Hash produced with boto3: 66793fed3e21e38ebc46493a9e8c46c4
Hash produced with s3fs: c86cf89971dfb3806166afc92a050492

boto3==1.9.202
s3fs==0.3.2
Hash produced with boto3: 66793fed3e21e38ebc46493a9e8c46c4
Hash produced with s3fs: c86cf89971dfb3806166afc92a050492

boto3==1.9.202
s3fs==0.3.3
Hash produced with boto3: 66793fed3e21e38ebc46493a9e8c46c4
Hash produced with s3fs: c86cf89971dfb3806166afc92a050492
```

Each of these was produced with the following code:
```python
import hashlib

import boto3
import s3fs

def md5(fname):
    hash_md5 = hashlib.md5()
    with open(fname, "rb") as f:
        for chunk in iter(lambda: f.read(4096), b""):
            hash_md5.update(chunk)
    return hash_md5.hexdigest()

print(f"boto3=={boto3.__version__}")
print(f"s3fs=={s3fs.__version__}")

s3 = boto3.client("s3")
s3.download_file("****", "****/part-0-0", "/home/app/data/testing.boto")
print(f"Hash produced with boto3: {md5('/home/app/data/testing.boto')}")

fs = s3fs.S3FileSystem()
fs.get("s3://****/part-0-0", "/home/app/data/testing.s3fs")
print(f"Hash produced with s3fs: {md5('/home/app/data/testing.s3fs')}")
```

**Comment by TomAugspurger** [comment] 2019-08-29 20:36
Hmm thanks. Is this for arbitrary files, or are there specific ones you're seeing issues with?

**Comment by ewellinger** [comment] 2019-08-29 20:38
That's a good question and I unfortunately don't have a good answer.  It appears to be doing this to a handful of the same specific part files in this parquet file but I'm having trouble tracking down if there is anything in common between those part files.
e.g. part-0-0 is consistently getting corrupted while part-0-1 isn't

**Comment by TomAugspurger** [comment] 2019-08-29 20:40
Thanks. Can you also print out your version of fsspec for s3fs >= 0.3.0?

**Comment by ewellinger** [comment] 2019-08-29 20:45
Looks like `fsspec==0.4.3` for all of those outputs

**Comment by TomAugspurger** [comment] 2019-08-30 11:49
OK, could you also try with s3fs==0.3.4 (released yesterday)?

**Comment by ewellinger** [comment] 2019-08-30 15:28
That did it!  I'm curious what was causing the issue?

```
boto3==1.9.202
s3fs==0.3.4
Hash produced with boto3: 66793fed3e21e38ebc46493a9e8c46c4
Hash produced with s3fs: 66793fed3e21e38ebc46493a9e8c46c4
```

**Comment by TomAugspurger** [comment] 2019-08-30 15:41
It was the same root cause as https://github.com/dask/dask/issues/5336. https://github.com/dask/dask/issues/5336#issuecomment-526564639 has my best guess right now (bad interaction between our cache, and our moto vs. s3 behavior with bad range requests).

Sorry about that, but glad it's fixed now.

**Closed by TomAugspurger** 2019-08-30 15:41 UTC

**Comment by ewellinger** [comment] 2019-08-30 15:47
Gotcha, thanks for getting a fix out so fast!  🥇
