### ISSUE TITLE
'aiobotocore' has no attribute 'AioSession'

### ISSUE THREAD

**Issue by henrique-britoleao** [dask/s3fs#515] opened 2021-08-20 16:40 UTC
I am running a job on docker that uses s3fs and am installing it using pip. I am using python's 3.9.6 image and installing s3fs using pip via a requirements file. The behaviour is equivalent to running:

```bash
pip install s3fs==2021.07.0
```

At some point during the creation of the container, the job raises the following error:

```python-traceback
    File "/usr/local/lib/python3.9/site-packages/fsspec/asyn.py", line 25, in _runner
         result[0] = await coro
    File "/usr/local/lib/python3.9/site-packages/s3fs/core.py", line 641, in _find
        out = await self._lsdir(path, delimiter="", prefix=prefix)
    File "/usr/local/lib/python3.9/site-packages/s3fs/core.py", line 559, in _lsdir
        await self.set_session()
    File "/usr/local/lib/python3.9/site-packages/s3fs/core.py", line 378, in set_session
         self.session = aiobotocore.AioSession(**self.kwargs)
AttributeError: module 'aiobotocore' has no attribute 'AioSession'
```
The error only happens when running the code on the Docker container, it works fine locally. I have, however, noticed that the version of aiobotocore installed is 1.4.0 and in the changelogs they have specified that:

> 1.4.0 (2021-08-20)
> - fix retries via config #877
> - ***remove AioSession and get_session top level names to match botocore***

I fixed it by adding 

```
aiobotocore == 1.3.3
```

to the requirements file, but thought it could be useful to add support to the new version of aiobotocore.

**Comment by jrbourbeau** [comment] 2021-08-20 16:42
Thanks for raising an issue @henrique-britoleao. Closing as a duplicate of https://github.com/dask/s3fs/issues/514

**Closed by jrbourbeau** 2021-08-20 16:42 UTC
