### ISSUE TITLE
Refresh Default with True Parameter with List CMD

### ISSUE THREAD

**Issue by phdnzdeveloper** [dask/s3fs#526] opened 2021-08-30 22:20 UTC
Hi team

I would like to ask could we change default parameter of S3FileSystem.ls(**_refresh=False_**) to S3FileSystem.ls(**_refresh=True_**).  
We use a lot of s3fs library in our projects. every time we use it with list command, we quickly forgot default of s3fs refresh is **False**, which causes missing responses in result. It would be great, if we can change from False to True.

Thank you
Giang

**Comment by mouradmourafiq** [comment] 2021-08-30 22:24
We had a similar issue as well, not only the other libraries (gcs and azure) are not using the same function signature, but the cache is ignored in those libraries by default, we also had to change this behavior in a [subclass](https://github.com/polyaxon/polyaxon/blob/master/core/polyaxon/fs/s3.py#L30)

**Comment by martindurant** [comment] 2021-08-31 01:35
Does the `use_listings_cache=False` option not provide everything you need?

> the cache is ignored in those libraries by default.

What do you mean?


In general, I agree that the listings caching system could use an overhaul, we can carefully plan how it should work and what options should be available.

**Comment by mouradmourafiq** [comment] 2021-08-31 08:09
>     the cache is ignored in those libraries by default.
> What do you mean?

Sorry about how my message sounded, I think during the migration to fsspec and the cloud fs libraries, we found a couple of inconsistencies in term of behavior (default values) and the signature of the functions.

We use `use_listings_cache` to handle the cache behavior, but I think somehow s3fs did not take that flag into consideration during the listing, we had to pass `refresh=True` manually. Also in adlfs the flag is called `invalidate_cache` instead of `refresh`.

**Comment by martindurant** [comment] 2021-08-31 12:35
`use_listings_cache` is an argumuent to `__init__`, and `invalidate_cache` is a method. Here is a test, as it would appear in s3fs's test suite, showing that they work as expected.
```python

def test_dircache(s3):
    assert list(s3.dircache) == []
    s3.ls(test_bucket_name)
    assert list(s3.dircache) == [test_bucket_name]
    s3.invalidate_cache()
    assert list(s3.dircache) == []

    s32 = S3FileSystem(anon=False, client_kwargs={"endpoint_url": endpoint_uri},
                       use_listings_cache=False)

    s32.ls(test_bucket_name)
    assert list(s32.dircache) == []
```

**Comment by mouradmourafiq** [comment] 2021-08-31 12:42
Thanks for the response, I know that it's an argument for the `__init__` function, and this is how we pass it to the [various classes](https://github.com/polyaxon/polyaxon/blob/master/core/polyaxon/fs/fs.py#L44) however, the `ls` was cached in s3fs for some reason and did not respect that argument, so we had to pass force refresh. I might be wrong, we have spent over 20 days testing various configurations and artifacts stores before releasing to production with the fsspec logic.

In any case, the libraries are working perfectly and we have since removed similar logic that we were maintaining ourselves, so thank you for all the work on this project. We still have to handle some minor warnings and exception handling when we try to close the connections, but that's not urgent at the moment.

**Comment by martindurant** [comment] 2021-08-31 12:47
If you can provide reproducers along the lines of the test I show above, I would be happy to fix the problem.

**Comment by mouradmourafiq** [comment] 2021-08-31 12:53
Thank you. As soon as I can find some time, I will remove `refresh=True` from the code and test again and see if it was a configuration issue from our side, if not I will try to formulate a reproducible example.

**Comment by martindurant** [comment] 2021-08-31 12:55
OK, thank you. I will close this issue for now, and please reopen if you have that example for me.

**Closed by martindurant** 2021-08-31 12:55 UTC
