### ISSUE TITLE
S3FileSystem.exists throwing inaccurate FILENOTFOUND

### ISSUE THREAD

**Issue by chitzinwin** [dask/s3fs#253] opened 2019-10-30 18:24 UTC
#53 

I am still having the same issue when I am trying to create dask dataframe form s3. I did make sure `anon=False`  when I create the interface object. It is a sporadic problem. Not sure why. I have troubleshot my code with boto3 s3 client and s3 object. They both agreed the file is on S3 but s3fs `exists`  is returning 'Filenotfound'.

 ```
client  = boto3.client('s3')
def check(s3, bucket, key):
    try:
        r=s3.head_object(Bucket=bucket, Key=key)
    except ClientError as e:
        return int(e.response['Error']['Code']) != 404 #e.response['Error'] #
    return True

 check(client, bucket, key))
#########################################################

resource = boto3.resource('s3')

 s3resource.Object(bucket,key).get()
 except botocore.exceptions.ClientError as e:
                          if e.response['Error']['Code'] == "404":
                                return False
                          else: raise
else:
         return True

```

**Comment by martindurant** [comment] 2019-10-31 19:56
Sorry, I don't follow, what code are you executing and what do you expect? The code above seems to be boto only.

**Comment by chitzinwin** [comment] 2019-11-08 18:02
@martindurant 
my code to read the csv form s3 is pretty straightforward:

```
import dask.dataframe as dd

dd.read_csv("s3://bucket/key/file.csv")
```

I am confident the file is there. But when I invoke it especially right after the file is created, this line is giving me FILENOTFOUND. 

I triggered to read the file based on the completion of upload event to S3 bucket. In other words, you may rule out the doubt that I am reading before the file has been created. 

Thank you

**Comment by martindurant** [comment] 2019-11-08 18:09
If you create the file elsewhere, the s3 instance likely has retained the old directory listing and doesn't see the new file. Does 
```
fsspec.filesystem('s3').invalidate_cache()
```
before read_csv fix this?

@TomAugspurger , I wonder, should we at least optionally turn off file listings caching altogether? There are now many people struggling with this (was not the case before), possible because of instance caching. Perhaps it's the latter we should turn off...

**Comment by chitzinwin** [comment] 2019-11-08 19:08
@martindurant ,
Thank you for your prompt reply. 

I have added that line before every reading.  The error still occurred once after a few files uploaded to S3.

**Comment by martindurant** [comment] 2019-11-08 19:10
Note that S3 also guarantees only "eventual consistency" of data and listings, so it is possible that the file is not (yet) reported as existing even though it arrived at the destination servers. You may want to wait a bit...

**Comment by TomAugspurger** [comment] 2019-11-08 19:42
I don't really understand the bug report.

> If you create the file elsewhere, the s3 instance likely has retained the old directory listing and doesn't see the new file.

I think we need to be clear about the behavior of the file listings cache. By using it, you need to be aware that external systems can change the state of the filesystem (by adding or removing files), making the cache invalid.

And it does seem like we should offer an option to disable file caching entirely.

**Comment by chitzinwin** [comment] 2019-11-08 20:39
@martindurant ,
To make sure I am getting it right:
'eventual consistency' means the data uploaded to S3 won't appear in the listing on the bucket even after upload was completely done?

But using boto3.resoure('s3'), the confirmed the existence of the object though.

**Comment by martindurant** [comment] 2019-11-08 20:42
I'm saying that could be the case, depending on when exactly you make the call. I only suggest it because you are trying to read immediately after creation, and the creation is from some other service

**Comment by chitzinwin** [comment] 2019-11-08 21:04
@martindurant 
 To give a sense of how I am using s3fs, I would like to list the general work flow:

1. Programmatically upload csv to S3 via nodejs client
2. Once upload is complete, S3 return the notification on the object creation event with its ETag back to nodejs cllient.
3. Only then nodejs client triggers aws_lambda function with the ETag of the object
4. Aws-lambda funciton constructs path to s3 from Etag  and pass it  dask + s3fs  to read the csv file.

**Comment by chitzinwin** [comment] 2019-11-08 21:09
@martindurant 

The above workflow works most of the times. But to be foolproof, Do you think I should add delay before accessing file? 

Thanks a lot

**Comment by martindurant** [comment] 2019-11-08 21:15
It is just a guess, I imagine it doesn't hurt, although s3fs is really just calling boto too, so they ought to agree.
However, if the only thing you are doing is fetching the file in one go, then s3fs's file-system capabilities may be more than you need, and indeed boto may be enough (or `s3fs.core._fetch_range`).

**Comment by chitzinwin** [comment] 2019-11-08 21:30
@martindurant 

Thank you again for your input. It is my current thought too, rolling back to boto3. 
At the same time I want to reserve the room of salability. That is my dilemma. The file size I am expecting is from the range of 500KB to 3GB.

The feature I am currently relying on is the efficiency of dask+s3fs in partitioning for my ad-hoc clustering in lambda.

Breaking down, I can get the almost uniform chunk  out of big csv into delays, then serialized and spawned out to multiple lambda functions as an ad-hoc cluster. All functions will do the same job in parallel. There is no data dependency between them. So, It works.

Do you think  I can get the dask dataframe with custom partition size using boto3?

**Comment by martindurant** [comment] 2019-11-14 20:18
Sure you can of course call boto3 from a delayed function if you like, as you could call any python code; but it would still be good to debug why s3fs isn't picking it up for you following invalidate_cache(). Did you try waiting a little while?

**Comment by chitzinwin** [comment] 2019-11-15 01:54
@martindurant , Sorry I forgot to follow up this issue.  

I got the delayed function piece. But I am not getting how I can get the partitions out of a big csv without using the read_csv with s3fs:

```
dd.read_csv("s3://bucket/key/file.csv", dtype=str, na_filter=False, blocksize="128MB")
```
#####################################################################
I did call the invalidate_cache, plus added 2 seconds delay if the first access to file got FILENOTFOUND error. Do you want me to invalidate_cache after delay?

Although this reduces the number of FILENOTFOUND error occurrence, it still happens when I do a series of upload. About 10 files. It is significant improvement compared to every 4 or 5 uploads to S3.

My current implementation is as below:

```
import fsspec
import dask.dataframe as dd

fsspec.filesystem('s3').invalidate_cache()

try:
            dd.read_csv("s3://bucket/key/file.csv")
    
except:
                  time.sleep(2)
                  print("Second attempt after 2 sec sleep")
                  dd.read_csv("s3://bucket/key/file.csv")


```

With the above code, I can see the print statement in cloudwatch if the first attempt failed. I can see FILENOTFOUND error twice if both attempts failed. I don't want to increase the delay.

Thank you

**Comment by martindurant** [comment] 2019-11-15 16:18
When you try to find the same file from your local system, do you see the file?
What exactly does your notification provide? 
You could try to use `s3.url()` to generate an access URL and use that whether the file is listed or not - use that https url instead of the s3 one.

**Comment by chitzinwin** [comment] 2019-11-15 19:30
@martindurant , 
Yes I see the file exists in S3 bucket. My trigger message related to S3 is liked below:

```
{
input:
          {
           bucket: buck_name,
            filepath: "main/sub/sub/file.csv"
        }
}
```

`s3.url()` I will give it a try and let you know.

**Comment by scuddalo** [comment] 2019-11-18 21:20
We are running into this exact issue in our project too, @martindurant. We would greatly appreciate any updates/workarounds.

**Comment by martindurant** [comment] 2019-11-19 16:20
It would be useful to probe exactly where the error is coming from, which may take extra logging or pdb probing: clearly s3fs must be making an extra call somewhere that boto is not. I don't know that we are in a position to do this, since we've never seen the problem!

**Comment by abdullin** [comment] 2019-11-22 11:37
We have encountered a similar problem: `S3fs.exists` and `s3fs.open` fail to find a file, while another client opens it without any problem.

If I understand correctly, S3FS uses a `ls` operation whenever `exists` is used. `ls` is limited to 1000 files. If the desired file is not present within the first 1000 files that `ls` retrieves, then `exists` will return `False`.

**Comment by TomAugspurger** [comment] 2019-11-22 12:10
@abdullin is your `path` a "directory" or a file?

Where do you see that only the first 1,000 files are returned from `ls`?

**Comment by abdullin** [comment] 2019-11-22 12:39
@TomAugspurger we were checking for the existence of the file in a dense folder. While stepping through the codebase with the debugger, it leads to `exists` -> `info` -> `ls`, where the result of `ls` is exactly 1000 files. The folder itself contains 4226 files and the file in question is the last one (given the sorting by name).

The fact that `ls` returns only first 1000 files is a known issue. We are always using a custom paginator to list directory contents.

**Comment by martindurant** [comment] 2019-11-22 14:28
There are two things here:
- info() should call HEAD on the object if the dir is not in the cache. This has been discussed elsewhere, but I can't find it now (and is the way ti works for version_aware buckets)
- the directory listing does use a paginator, but perhaps there is an implicit argument setting the number of results to 1000?

**Comment by nojohnny101** [comment] 2019-11-23 03:02
I am also facing this problem. We are landing parquet files from an external ETL tool to a S3 bucket that then triggers a lambda to process it. We are using the pyarrow library which uses the s3fs library to interact with S3.

Because the pyarrow library is quite large, the first time the lambda kicks off it takes more time to execute and process the parquet file. Any subsequent executions that occur are "warm" starts because our frequency is so high and all of those subsequent ones were failing. The related stack trace was this:

```
[ERROR] OSError: Passed non-file path: s3://bucket/schedule/source/schema_name/table_name/trunc/20191122024436.parquet
Traceback (most recent call last):
  File "/var/task/file_check.py", line 35, in lambda_handler
    main(event, context)
  File "/var/task/file_check.py", line 260, in main
    validate_resp['object_type'])
  File "/opt/python/utils.py", line 80, in schema_check
    stage_pya_dataset = ParquetDataset(full_URL_stage, filesystem=s3)
  File "/opt/python/lib/python3.7/site-packages/pyarrow/parquet.py", line 1030, in _init_
    open_file_func=partial(_open_dataset_file, self._metadata)
  File "/opt/python/lib/python3.7/site-packages/pyarrow/parquet.py", line 1229, in _make_manifest
    .format(path))
```

This aligns with what others have described here. Possibly due to eventual consistency but I think there is more at work here.

At first I tried sleeping but this barely helped. As suggested, I implemented this and it helped greatly.
`fsspec.filesystem('s3').invalidate_cache()`
Can you explain why this helps?

Would be more than happy to help to get to the root cause of this.

**Comment by chitzinwin** [comment] 2019-11-24 05:06
> 
> 
> When you try to find the same file from your local system, do you see the file?
> What exactly does your notification provide?
> You could try to use `s3.url()` to generate an access URL and use that whether the file is listed or not - use that https url instead of the s3 one.

Sorry for the delay, 

I let my lambda instance ran with s3.url() throughout last week. This function basically returns the singed url to s3 object with expiration. Therefore, dask will treat the object's origin as a web server. 

Looking at the cloudwatch, I could confirm it avoided FILENOTFOUND 100%.
```
dd.read_csv(s3.url('s3://bucket/key')) #using http 
``

But, I am still having issue with the partition when I try to read s3 object with custom partition size. The is because the headers does not have Content-Length property. To investigate the Http(s) access to obejct, I used `requests` like below:
```
requests.head(s3.url(('s3://bucket/key')).status_code
``` 
Things get weirder when status_code says 403 which is permission issue, however, when I do dd.read_csv(s3.url('s3://bucket/key')).compute(), I am getting the dataframe without any error. Ran 10 times. Succeeded 10 times.  

Further investigation with requests:
```
requests.head(s3.url(('s3://bucket/key')).headers
```
Etag is one of the headers but not content-length. So I can get content-length separately using `s3client.head_object(Bucket=bkt, Key=k)` [reference'[https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/s3.html#S3.Client.head_object) but I can't include in the header unless I have proper [storage_option](https://docs.dask.org/en/latest/remote-data-services.html) format for s3. 

@martindurant , Is there anything like minimal `storage_option` config for s3 as a reference?

**Comment by dylancis** [comment] 2020-01-23 13:51
Exacatly same error here - randomly file not found.

**Comment by rajkumarmfd** [comment] 2020-07-02 19:39
> I am also facing this problem. We are landing parquet files from an external ETL tool to a S3 bucket that then triggers a lambda to process it. We are using the pyarrow library which uses the s3fs library to interact with S3.
> 
> Because the pyarrow library is quite large, the first time the lambda kicks off it takes more time to execute and process the parquet file. Any subsequent executions that occur are "warm" starts because our frequency is so high and all of those subsequent ones were failing. The related stack trace was this:
> 
> ```
> [ERROR] OSError: Passed non-file path: s3://bucket/schedule/source/schema_name/table_name/trunc/20191122024436.parquet
> Traceback (most recent call last):
>   File "/var/task/file_check.py", line 35, in lambda_handler
>     main(event, context)
>   File "/var/task/file_check.py", line 260, in main
>     validate_resp['object_type'])
>   File "/opt/python/utils.py", line 80, in schema_check
>     stage_pya_dataset = ParquetDataset(full_URL_stage, filesystem=s3)
>   File "/opt/python/lib/python3.7/site-packages/pyarrow/parquet.py", line 1030, in _init_
>     open_file_func=partial(_open_dataset_file, self._metadata)
>   File "/opt/python/lib/python3.7/site-packages/pyarrow/parquet.py", line 1229, in _make_manifest
>     .format(path))
> ```
> 
> This was failing within the pyarrow library when it was calling
> `fs.isfile(path)`
> 
> fs being the s3fs system I passed in via:
> `s3 = s3fs.S3FileSystem()`
> 
> This aligns with what others have described here. Possibly due to eventual consistency but I think there is more at work here.
> 
> At first I tried sleeping but this barely helped. As suggested, I implemented this and it helped greatly.
> `fsspec.filesystem('s3').invalidate_cache()`
> Can you explain why this helps?
> 
> Would be more than happy to help to get to the root cause of this.

hi johnny,
I'm facing the same issue.. did you resolve it?

**Comment by nojohnny101** [comment] 2020-07-03 01:46
@rajkumarmfd as I stated in my post, adding `fsspec.filesystem('s3').invalidate_cache()` after each call to s3 seems to have solved the problem permanently for us. for example if we are processing 2 s3 objects in a bucket, after we read in each one with pyarrow library, before processing the next one, we call the above command.

Hope this helps.

**Comment by chitzinwin** [comment] 2020-07-10 00:34
Okay, this has been an ongoing frustrating problem. In recent weeks, I got a chance to raise this issue to AWS support:

This is my case I explained to them:
Upon the create/put object event, the step functions was triggered which in turn triggers a Lambda function that attempts to retrieve HeadObject  like so below:
s3resource.Object(bucket, s3key).content_length
Every once in a while (about 5% of the time), this head operation fails with this error: “An error occurred (404) when calling the HeadObject operation: Not Found“.
 However, when we trigger Lambda function manually with the same payload immediately afterwards, it works fine.

AWS Response:

Hello, Hope you are doing well. I am ____ from AWS Premium Support and I would be assisting you further with this case today. Firstly please accept my sincere apologies on behalf of AWS for the delayed response. For my understanding, every once in a while (maybe 5% of the time), you are getting a 404 error when calling operations HeadObject or GET. Please feel free to correct me if my understanding is wrong. 

 Answers ------------------- 
From our documentation: Amazon S3 achieves high availability by replicating data across multiple servers within AWS data centers. If a PUT request is successful, your data is safely stored. However, information about the changes must replicate across Amazon S3, which can take some time, and so you might observe the following behaviors:
 a- A process writes a new object to Amazon S3 and immediately lists keys within its bucket. Until the change is fully propagated, the object might not appear in the list. 
 b- A process replaces an existing object and immediately tries to read it. Until the change is fully propagated, Amazon S3 might return the previous data. 
 c- A process deletes an existing object and immediately tries to read it. Until the deletion is fully propagated, Amazon S3 might return the deleted data. 
 d-A process deletes an existing object and immediately lists keys within its bucket. Until the deletion is fully propagated, Amazon S3 might list the deleted object. 

Having said that, you mentioned that if you re-try again you are able to GET or HeadObject the object. This is an expected behavior that it match with the first point explained above (a-), due to the short time between the creation of the object and the list (GET or HeadObject) of it. Below, in the Resources section, I will share with you some performance and design recommendations for Amazon S3, which talks about re-try logic, aggressive timeouts and exponential back-offs, please check the following links: - [1] [Performance Design Patterns for Amazon S3](https://docs.aws.amazon.com/AmazonS3/latest/dev/optimizing-performance-design-patterns.html) - [2] [Performance Design Patterns for Amazon S3 - Timeouts and Retries for Latency-Sensitive Applications](https://docs.aws.amazon.com/AmazonS3/latest/dev/optimizing-performance-design-patterns.html#optimizing-performance-timeouts-retries) - [3][ Error Retries and Exponential Backoff in AWS ](https://docs.aws.amazon.com/general/latest/gr/api-retries.html)

**Comment by martindurant** [comment] 2020-07-10 16:52
Would the solution perhaps be to add a delay before starting the process? I diidn't gather from the description what the typical timescales are.

You could also change the class attributes relating to this:

```
    retries = 5
    read_timeout = 15
```
or wrap the call to s3fs with a further retry loop on a longer timescale.

**Comment by chitzinwin** [comment] 2020-07-13 16:36
@martindurant 
I think you are talking about ```connect_timeout``` and ```read_timeout``` from ```botocore.config.Config```. Those does not help for exponential back-offs. 

I wrap the call using the logic from the third option [3] Error Retries and Exponential Backoff in AWS 

`Do some asynchronous operation.

retries = 0

DO
    wait for (2^retries * 100) milliseconds

    status = Get the result of the asynchronous operation.

    IF status = SUCCESS
        retry = false
    ELSE IF status = NOT_READY
        retry = true
    ELSE IF status = THROTTLED
        retry = true
    ELSE
        Some other error occurred, so stop calling the API.
        retry = false
    END IF

    retries = retries + 1

WHILE (retry AND (retries < MAX_RETRIES))`

**Comment by martindurant** [comment] 2020-07-17 13:40
I am in the middle of a big refactor to add async support and batch operations to s3fs - more operations should be going through the normal retry logic. Please check back after that is merged, and we can deal with this issue. A good demonstration test would be the best start, of the form that can be added to the test suite (although I don't know how we can persuade moto to fail occasionally).

**Comment by mdwint** [comment] 2020-09-08 12:58
I'm also experiencing this issue on s3fs 0.5.0, but I've found no way to reproduce it consistently.

```python
Traceback (most recent call last):
  File "/code/.venv/lib/python3.7/site-packages/dask/dataframe/io/parquet/core.py", line 239, in read_parquet
    **kwargs,
  File "/code/.venv/lib/python3.7/site-packages/dask/dataframe/io/parquet/arrow.py", line 656, in read_metadata
    paths, fs, split_row_groups, gather_statistics, filters, dataset_kwargs
  File "/code/.venv/lib/python3.7/site-packages/dask/dataframe/io/parquet/arrow.py", line 166, in _gather_metadata
    dataset, base, fns = _get_dataset_object(paths, fs, filters, dataset_kwargs)
  File "/code/.venv/lib/python3.7/site-packages/dask/dataframe/io/parquet/arrow.py", line 150, in _get_dataset_object
    dataset = pq.ParquetDataset(paths[0], filesystem=fs, **kwargs)
  File "/code/.venv/lib/python3.7/site-packages/pyarrow/parquet.py", line 1170, in __init__
    open_file_func=partial(_open_dataset_file, self._metadata)
  File "/code/.venv/lib/python3.7/site-packages/pyarrow/parquet.py", line 1365, in _make_manifest
    .format(path))
OSError: Passed non-file path: bucket/dataset-directory
```

**Comment by martindurant** [comment] 2020-09-08 13:00
@mdwint , can you please supply the code that caused this. Note that the exception is apparently from the local file-system, not s3fs.

**Comment by mdwint** [comment] 2020-09-08 14:37
This is part of a distributed application, which makes it tricky to reproduce. The code that caused the error is equivalent to `dd.read_parquet("s3://bucket/dataset-directory/")` (with `s3://` and a trailing slash). This call is nested in a loop over many URLs, most of which succeed. The failure occurs in only a small percentage of cases, and the files surely exist on S3, but may have been recently created (seconds ago). I'm certain that the URLs are correct, and that s3fs is installed and configured.

**Comment by martindurant** [comment] 2020-09-08 14:41
> the files surely exist on S3, but may have been recently created (seconds ago)

S3 does not necessarily list files that have been created very recently, because it is a distributed storage system, and it takes time for metadata to propagate. It only offers "eventual consistency".
Furthermore, s3fs's implementation normally cached directory listings, because these lookups can be expensive. You can turn off this caching system to force refresh on every access, or explicitly bin the cache with `.invalidate_cache()` before the calls that matter.

**Comment by mdwint** [comment] 2020-09-08 15:28
Thanks, @martindurant! I will try passing `use_listings_cache=False` to S3FileSystem.

**Comment by jstromergalley** [comment] 2020-10-22 16:46
I want to echo an important thing raised by @mdwint .

I am also getting an **exists()** failure on a path that ends with a "/".  This used to work.  These are files that have existed for months in S3.

```
exists("bucket/pseudo_folder_name") --> True
exists("bucket/pseudo_folder_name/") --> False
exists("bucket/pseudo_folder_name/pseudo_file_name") --> True

```

**Comment by martindurant** [comment] 2020-10-22 16:55
OK, got it - this only happens if the parent directory has been listed first, and is actually coded in `fsspec.AbstractFileSystem._ls_from_cache`.

**Comment by jstromergalley** [comment] 2020-10-22 17:05
Thanks @martindurant 

I can pass in a use_listings_cache=False suring init for now (or forever if this is not a bug). Is it a bug?

**Comment by martindurant** [comment] 2020-10-22 17:07
Yes, that workaround should be fine, although I expect you end up doing more listing operations.

**Closed** 2020-10-22 19:29 UTC

**Comment by melvinev** [comment] 2020-11-14 18:12
Is there an environment variable I can use to set this globally?

use_listings_cache=False

**Comment by melvinev** [comment] 2020-11-14 19:05
s3fs.S3FileSystem.cachable = False or is there  S3FS config file I can set this globally?

**Comment by martindurant** [comment] 2020-11-16 20:06
fsspec has a config, with which you can configure the value of any kwarg you don't explicitly pass, see https://filesystem-spec.readthedocs.io/en/latest/features.html#configuration
This only works if you use the fsspec entry functions (filesystem, open..) rather than calling S3FileSystem directly.
s3fs.S3FileSystem.cachable affects the caching of instances, not directory listings.

**Comment by melvinev** [comment] 2020-11-16 20:09
Thank you @martindurant I am trying having issues where dask is reading from a stale S3 directory listing using S3FS via dd.read_parquet('path').  I want to make sure it rebuilds the S3 directory cache each time (even though it is expensive), does this setting accomplish this globally?

s3fs.S3FileSystem.cachable = False

**Comment by martindurant** [comment] 2020-11-16 20:12
> s3fs.S3FileSystem.cachable affects the caching of instances, not directory listings.

No, that setting is for whether instances can be cached and has nothing to do with directory listings. You can use the config system, as I said with, for example `use_listings_cache=False`.

**Comment by melvinev** [comment] 2020-11-16 20:16
Ah okay got it thank you.

Is there an environment variable I can set for this? use_listings_cache=False

**Comment by martindurant** [comment] 2020-11-16 20:20
https://filesystem-spec.readthedocs.io/en/latest/features.html#configuration

Environment variables only really work for strings, and an empty string looks a lot like the variable not being set at all, so I don't think so.

**Comment by joeree** [comment] 2021-01-14 20:55
Hello, the problem is not consistent, but we're finding periodic failures in our code to find files in S3.
Our code:
```
self.s3_file_system = s3fs.S3FileSystem
[...]
s3_path = f's3://{self.bucket}/{self.PREFIX}/{storage_key}'
        if self.s3_file_system.exists(s3_path):
            raise S3FileExistsError(s3_path)
```
Like I said, it's not consistent but happens about 2% of the time.

**Comment by martindurant** [comment] 2021-01-18 15:02
@joeree , you may want to play with the parameters of the directory listings cache or to invalidate the cache explicitly yourself. Can you identify what situations cause the problem?

**Comment by oeway** [comment] 2021-02-04 21:57
Hi, I am having a similar issue,  when I do `fs.glob('/test-bucket/folder/image.*')` it returns `[]`, but if I do `fs.glob('/test-bucket/folder/image.png')` it returns True, and I know the file exists in the bucket. I try to fix it with `use_listings_cache=False`, and it seems working. 

However, it cause issues for my other part where I have `fs.rm('/path/to/a/folder', recursive=True)`. 

Here is the error:
```
self = <fsspec.dircache.DirCache object at 0x7fe9dc858cd0>, item = 'test-bucket'

    def __getitem__(self, item):
        if self.listings_expiry_time:
            if self._times.get(item, 0) - time.time() < -self.listings_expiry_time:
                del self._cache[item]
        if self.max_paths:
            self._q(item)
>       return self._cache[item]  # maybe raises KeyError
E       KeyError: 'test-bucket'

../../miniconda3/envs/engine/lib/python3.7/site-packages/fsspec/dircache.py:62: KeyError
```

Any idea?

**Comment by joeree** [comment] 2021-04-21 13:58
> @joeree , you may want to play with the parameters of the directory listings cache or to invalidate the cache explicitly yourself. Can you identify what situations cause the problem?

@martindurant I'm sorry that I just saw your post. No we are unable to figure out the circumstances that cause the problems, only that they are sporadic but annoying when they do occur. We've had to switch this particular part over to boto3 to resolve the problem.

**Comment by mohamedniyaz1996** [comment] 2022-03-14 15:37
Try out the latest version of s3fs (2022.2.0) as it is build on **aiobotocore** (https://aiobotocore.readthedocs.io/en/latest/) which offers full asynchronous support for AWS services like S3, SQS, DynamoDB.

Previous versions of s3fs were built on boto which doesn't seems to be managing eventual consistency of AWS S3.

**Comment by GaoDalie** [comment] 2025-07-14 22:44
ds_hourly = catalog["CORA-V1.1-fort.63-timeseries"].to_dask()
ds_hourly_sel = ds_hourly.sel(time=slice("2002-02-12", "2002-02-13")).compute()
ds_hourly_sel

---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
Cell In[8], line 1
----> 1 ds_hourly = catalog["CORA-V1.1-fort.63-timeseries"].to_dask()
      2 ds_hourly_sel = ds_hourly.sel(time=slice("2002-02-12", "2002-02-13")).compute()
      3 ds_hourly_sel

File ~/Desktop/dead_zone/myenv/lib/python3.13/site-packages/intake_xarray/base.py:10, in IntakeXarraySourceAdapter.to_dask(self)
      8     return self.reader(chunks={}).read()
      9 else:
---> 10     return self.reader.read()

File ~/Desktop/dead_zone/myenv/lib/python3.13/site-packages/intake/readers/readers.py:121, in BaseReader.read(self, *args, **kwargs)
    119 kw.update(kwargs)
    120 args = kw.pop("args", ()) or args
--> 121 return self._read(*args, **kw)

File ~/Desktop/dead_zone/myenv/lib/python3.13/site-packages/intake/readers/readers.py:1327, in XArrayDatasetReader._read(self, data, open_local, **kw)
   1325         f = fsspec.open(data.url, **(data.storage_options or {})).open()
   1326         return open_dataset(f, **kw)
-> 1327 return open_dataset(data.url, **kw)

File ~/Desktop/dead_zone/myenv/lib/python3.13/site-packages/xarray/backends/api.py:715, in open_dataset(filename_or_obj, engine, chunks, cache, decode_cf, mask_and_scale, decode_times, decode_timedelta, use_cftime, concat_characters, decode_coords, drop_variables, create_default_indexes, inline_array, chunked_array_type, from_array_kwargs, backend_kwargs, **kwargs)
    703 decoders = _resolve_decoders_kwargs(
    704     decode_cf,
...
    771         "Reference-FS's target filesystem must have same value"
    772         "of asynchronous"
    773     )

ValueError: Reference-FS's target filesystem must have same valueof asynchronous

Please any anyone has the same problem, i tried all ways but i couldn't figure it out from where the problem coming
